apiVersion: v2
appVersion: v2.3.4
description: A Helm chart for customising the deployment of the Red Hat GitOps Operator ðŸ”«
name: gitops-operator
version: 0.3.8
home: https://github.com/redhat-cop/helm-charts
icon: https://raw.githubusercontent.com/eformat/openshift-gitops/main/rh-gitops.png
maintainers:
- name: eformat
- name: springdo
