apiVersion: v2
name: ploigos
description: A Helm chart for Ploigos - Trusted Software Supply Chain
type: application
version: 0.0.8
appVersion: 0.2.7
home: https://github.com/redhat-cop/helm-charts
maintainers:
- name: eformat
