apiVersion: v2
appVersion: v2.0.1
description: A Helm chart for customizing the deployment of the Ansible Automation Platform Operator
name: ansible-automation-platform
version: 0.0.3
home: https://github.com/redhat-cop/helm-charts
maintainers:
- name: paulbarfuss
- name: ecda909
