---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: {{ .Values.application.environments.development }}
  namespace: {{ .Values.application.environments.cicd }}
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: {{ .Values.application.environments.production }}
  namespace: {{ .Values.application.environments.cicd }}
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: nodejs-image-development
  namespace: {{ .Values.application.environments.cicd }}
  labels:
    app: {{ .Values.application.name }}
spec:
  type: image
  params:
    - name: url
      value: image-registry.openshift-image-registry.svc:5000/{{ .Values.application.environments.development }}/{{ .Values.application.name }}
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: nodejs-image-production
  namespace: {{ .Values.application.environments.cicd }}
  labels:
    app: {{ .Values.application.name }}
spec:
  type: image
  params:
    - name: url
      value: image-registry.openshift-image-registry.svc:5000/{{ .Values.application.environments.production }}/{{ .Values.application.name }}