apiVersion: v2
name: helper-status-checker
description: A helper Chart that creates a job to verify if the deployments of an operator are running. To do so it creates a service account with a role to read the status of the Deployments.
version: 4.0.10
home: https://github.com/redhat-cop/helm-charts
maintainers:
  - name: tjungbauer
    email: tjungbau@redhat.com
    url: https://blog.stderr.at/
keywords:
  - helper
  - subchart
