apiVersion: v1
appVersion: "v0.0.1"
description: A Helm chart for deploying Jenkins on OpenShift
name: jenkins
version: 0.0.7
home: https://github.com/rht-labs/helm-charts
maintainers:
  - name: springdo
  - name: ckavili
