apiVersion: v1
appVersion: 3.23.0
description: Sonatype Nexus is an open source repository manager
home: https://github.com/redhat-cop/helm-charts
name: sonatype-nexus
sources:
- https://github.com/sonatype/nexus-public
version: 0.0.3
maintainers:
  - name: eformat
