{{- if .Values.deployment }}
---
apiVersion: apps.openshift.io/v1 
kind: DeploymentConfig
metadata:
  annotations:
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
spec:
  replicas: 1
  selector:
    name: {{ .Values.appName }}
  strategy: {{- if .Values.persistence.enabled }}
    type: Recreate 
    {{ else }}
    type: Rolling 
    {{- end }}
  template:
    metadata:
      labels:
        name: {{ .Values.appName }}
    spec:
      containers:
      - name: {{ .Values.appName }}
        env: {{ if .Values.deployment.openshiftauth }}
        - name: OPENSHIFT_ENABLE_OAUTH
          value: "true"
        - name: OPENSHIFT_ENABLE_REDIRECT_PROMPT
          value: "true" 
          {{- end }}
        - name: KUBERNETES_MASTER
          value: https://kubernetes.default:443
        - name: KUBERNETES_TRUST_CERTIFICATES
          value: "true"
        - name: JENKINS_SERVICE_NAME
          value: {{ .Values.appName }}
        - name: JNLP_SERVICE_NAME
          value: {{ .Values.appName }}-jnlp
        {{- range $key := .Values.deployment.env_vars }}
        {{- if .value }}
        - name: {{ .name }}
          value: {{ .value | default "" | quote }}
        {{- end }}
        {{- end }}
        image: ' '
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 2
          httpGet:
            path: /login
            port: 8080
          initialDelaySeconds: 420
          periodSeconds: 360
          timeoutSeconds: 240
        readinessProbe:
          httpGet:
            path: /login
            port: 8080
          initialDelaySeconds: 3
          timeoutSeconds: 240
        resources:
          requests:
            cpu: {{ .Values.deployment.limits.cpu_request | quote }}
            memory: {{ .Values.deployment.limits.memory_request | quote }}
          limits:
            cpu: {{ .Values.deployment.limits.cpu_limit | quote }}
            memory: {{ .Values.deployment.limits.memory_request | quote }}
        securityContext:
          capabilities: {}
          privileged: false
        terminationMessagePath: /dev/termination-log
        {{- if .Values.persistence.enabled }}
        volumeMounts:
        - mountPath: /var/lib/jenkins
          name: {{ .Values.appName }}-data {{ end }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      serviceAccountName: {{ .Values.appName }}
      {{- if .Values.persistence.enabled }}
      volumes:
      - name: {{ .Values.appName }}-data
        persistentVolumeClaim:
          claimName: {{ .Values.appName }}
      {{- end }}
  triggers:
  - imageChangeParams:
      automatic: true
      containerNames:
      - {{ .Values.appName }}
      from:
        kind: ImageStreamTag
        name: {{ .Values.deployment.imagestream.name}}:{{ .Values.deployment.imagestream.tag}}
        namespace: {{ .Values.deployment.imagestream.namespace}}
      lastTriggeredImage: ""
    type: ImageChange
  - type: ConfigChange
{{ end }}
