# Default values for owncloud.
replicaCount: 1

image:
  owncloud:
    repository: quay.io/eformat/owncloud-oauth
    pullPolicy: IfNotPresent
  redis:
    image: docker.io/redis:7.4@sha256:79676a8f74e4aed85b6d6a2f4e4e3e55d8a229baa7168362e592bbfdc67b0c9b
    healthimage: docker.io/healthcheck/redis:latest@sha256:06127d640e5c092f4707e3506e3a80c0361225b8da735b54d66e162a79d1fa38
    pullPolicy: Always
  mariadb:
    image: docker.io/mariadb:11.5@sha256:2d50fe0f77dac919396091e527e5e148a9de690e58f32875f113bef6506a17f5
    healthimage: docker.io/healthcheck/mysql:latest@sha256:b7a7b38485b0d93bfc12a42f870dcf8b27c9ba854c9a28d4d26ed941a113ee20
    pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name:

podSecurityContext: {}
securityContext: {}

service:
  owncloud:
    type: ClusterIP
    port: 8080
  redis:
    type: ClusterIP
    port: 6379
  mariadb:
    type: ClusterIP
    port: 3306

persistent:
  owncloud:
    accessMode: ReadWriteOnce
    volume:
      size: 100Gi
  redis:
    accessMode: ReadWriteOnce
    volume:
      size: 1Gi
  mariadb:
    accessMode: ReadWriteOnce
    volume:
      size: 10Gi

# OCP route
route: true
hostname: owncloud.apps.hivec.sandbox1604.opentlc.com
