# Default values for owncloud.
replicaCount: 1

image:
  owncloud:
    repository: quay.io/eformat/owncloud-oauth
    pullPolicy: IfNotPresent
  redis:
    image: docker.io/redis:7.2@sha256:f14f42fc7e824b93c0e2fe3cdf42f68197ee0311c3d2e0235be37480b2e208e6
    healthimage: docker.io/healthcheck/redis:latest@sha256:06127d640e5c092f4707e3506e3a80c0361225b8da735b54d66e162a79d1fa38
    pullPolicy: Always
  mariadb:
    image: docker.io/mariadb:11.3@sha256:e101f9db31916a5d4d7d594dd0dd092fb23ab4f499f1d7a7425d1afd4162c4bc
    healthimage: docker.io/healthcheck/mysql:latest@sha256:b7a7b38485b0d93bfc12a42f870dcf8b27c9ba854c9a28d4d26ed941a113ee20
    pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name:

podSecurityContext: {}
securityContext: {}

service:
  owncloud:
    type: ClusterIP
    port: 8080
  redis:
    type: ClusterIP
    port: 6379
  mariadb:
    type: ClusterIP
    port: 3306

persistent:
  owncloud:
    accessMode: ReadWriteOnce
    volume:
      size: 100Gi
  redis:
    accessMode: ReadWriteOnce
    volume:
      size: 1Gi
  mariadb:
    accessMode: ReadWriteOnce
    volume:
      size: 10Gi

# OCP route
route: true
hostname: owncloud.apps.hivec.sandbox1604.opentlc.com
