apiVersion: v2
name: ipa
description: A Helm chart for Kubernetes
# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 1.0.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
appVersion: 1.16.0
home: https://github.com/redhat-cop/helm-charts
icon: https://www.freeipa.org/images/freeipa/freeipa-logo-small.png
maintainers:
- name: springdo
- name: ckavili
- name: eformat
