apiVersion: v2
name: tekton-demo
description: This is an example of a pipeline developed in Tekton, the peaceful cat. It contains the main steps of a continuous software delivery process. It enforces a strict semantic version validation strategy, managing tag increments for you. Develop, Features, releases, patches and hotfixes flows are supported.
type: application
keywords:
  - tekton
  - pipeline
  - nodejs
  - github
maintainers: 
  - name: mvmaestri
icon: https://cd.foundation/wp-content/uploads/sites/78/2020/04/tekton-icon-color-1-300x300.png
home: https://github.com/redhat-cop/helm-charts
appVersion: latest
version: 0.0.1

