# Default values for tekton-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
cluster: apps.s45.core.rht-labs.com

application:
  name: nodejs-tekton
  version: 1.0.0
  runtime: nodejs:10 # default to node
  environments:
    development: nodejs-tekton-development
    production: nodejs-tekton-production
    cicd: nodejs-tekton-ci
  from:
    git:
      name: helm-charts
      url: https://github.com/mvmaestri/helm-charts
      revision: release/1.1.0
      submodules: '"false"'
      s2i:
        context: charts/tekton-demo/templates/app/src
        #angular-node-typescript-boiler

pipeline:
  name: nodejs
  sa:
    default: pipeline
    triggers: tekton-triggers-sa
  webhook:
    host: http://dev-nodejs-tekton-ci.apps.s45.core.rht-labs.com/
    github: 
      org: mvmaestri
      user: mvmaestri
      repo: helm-charts
      secret: github-webhook-secret
