cluster: apps.s45.core.rht-labs.com

application:
  name: do101
  runtime: nodejs:10
  environments:
    cicd: labs-ci-cd
    development: do101-development
    production: do101-production

pipeline:
  name: nodejs
  sa:
    default: pipeline
    triggers: tekton-triggers-sa
  nexus:
    host: https://nexus-labs-ci-cd.apps.s45.core.rht-labs.com/repository/labs-npm
  build:
    s2i:
      context: weather
  webhook:
    github: 
      org: mvmaestri
      user: mvmaestri
      repo: do101-apps
      secret: github-webhook-secret
      key: github-deploy-secret