# Default values for tekton-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
cluster: apps.s45.core.rht-labs.com

application:
  name: do101
  runtime: nodejs:10
  environments:
    cicd: do101-cicd
    development: do101-development
    production: do101-production
  from:
    git:
      url: https://github.com/mvmaestri/DO101-apps.git
      revision: master
      submodules: '"false"'
      s2i:
        context: weather

pipeline:
  name: nodejs
  sa:
    default: pipeline
    triggers: tekton-triggers-sa
  webhook:
    host: http://trigger-nodejs-tekton-cicd.apps.s45.core.rht-labs.com/
    github: 
      org: mvmaestri
      user: mvmaestri
      repo: DO101-apps
      secret: github-webhook-secret