apiVersion: v2
appVersion: "latest"
description: A Helm chart for deploying Pact Broker on OpenShift ðŸ”—
name: pact-broker
version: 0.0.10
home: https://github.com/redhat-cop/helm-charts
icon: https://img.stackshare.io/service/11305/pact.png
maintainers:
- name: mvmaestri
- name: gsampaio
- name: springdo
