kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ template "openshift-logforwarding-splunk.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: fluentd
{{ include "openshift-logforwarding-splunk.labels" . | indent 4 }}
