{{- range $key := .Values.secrets }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .name }}
spec:
  encryptedData:
    {{- .data | toYaml | nindent 4 }}
  template:
    metadata:
        {{- if .annotations }}
      annotations:
        {{- .annotations | toYaml | nindent 8 }}
        {{- end}}
        {{- if .labels }}
      labels:
        {{- .labels | toYaml | nindent 8 }}
        {{- end}}
      name: {{ .name }}
    type: {{ .type | default "opaque" | quote }}
{{- end }}
