apiVersion: v2
appVersion: "v1"
description: A Helm Chart for managing Sealed Secrets ğŸ•µï¸â€â™€ï¸ğŸ”
name: helper-sealed-secrets
version: 1.0.4
home: https://github.com/redhat-cop/helm-charts
icon: https://avatars.githubusercontent.com/u/34656521?s=400&v=4
maintainers:
  - name: springdo
  - name: ckavili
  - name: eformat
