apiVersion: v2
name: operatorhub
description: A Helm chart to create OperatorHub subscriptions
type: application
version: 0.0.4
appVersion: 0.0.2
home: https://github.com/redhat-cop/helm-charts
maintainers:
  - name: tylerauerbeck
  - name: ckavili
  - name: mabulgu
