{{- range .Values.operators }}
---
# create one Subscription per operator
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ .name }}
  namespace: {{ .namespace | default $.Release.Namespace }}
  labels:
    {{- include "operators-installer.labels" $ | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-40"
spec:
  channel: "{{ .channel }}"
  {{- if .config }}
  config:
    {{ .config | toYaml | indent 4 | trim }}
  {{- end }}
  installPlanApproval: "{{ .installPlanApproval }}"
  name: "{{ .name }}"
  source: "{{ .source }}"
  sourceNamespace: "{{ .sourceNamespace }}"
  startingCSV: "{{ .csv }}"
{{- end }}
