{{- with .Values }}
{{ if eq ( .enabled | toString) "true" }}
{{- range .checks }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .serviceAccount.name }}-{{ .namespace.name }}
  namespace: {{ .namespace.name | quote }}
  labels:
    {{- include "common.labels" $ | nindent 4 }}
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/sync-wave: {{ .syncwave | default 0 | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .serviceAccount.name }}-{{ .namespace.name }}
subjects:
  - kind: ServiceAccount
    name: {{ .serviceAccount.name | quote }}
    namespace: {{ .namespace.name | quote }}
{{- end }}
{{- end }}
{{- end }}
