apiVersion: v2
appVersion: v1.6.0
description: A Helm chart for customising the deployment of the ArgoCD Operator ⚓️
name: argocd-operator
version: 0.0.11
home: https://github.com/rht-labs/helm-charts
maintainers:
- name: springdo
- name: ckavili
- name: eformat
