apiVersion: v2
appVersion: v1.8.2
description: A Helm chart for customising the deployment of the ArgoCD Operator ⚓️
name: argocd-operator
version: 1.0.0
home: https://github.com/redhat-cop/helm-charts
maintainers:
- name: springdo
- name: ckavili
- name: eformat
- name: mabulgu
