apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: {{ .Values.pipeline.name }}
  namespace: {{ .Values.application.environments.cicd }}
  labels:
    app: {{ .Values.application.name }}
spec:
  resources:
    - name: {{ .Values.application.name }}-git
      type: git
    - name: {{ .Values.application.name }}-development
      type: image
    - name: {{ .Values.application.name }}-production
      type: image

  workspaces:
    - name: shared-workspace
    - name: upload
    - name: release-notes
    
  params:
    - name: ref
      description: Ref of the application
    - name: revision
      description: git unique head commit id
    - name: repourl
      description: repository full name
    - name: repofullname
      description: repository full name
    - name: author
      description: commit author username
    - name: email
      description: commit author email
    - name: message
      description: commit message
    - name: AUTHORS_API_KEY
      description: The OCP secret that contains DB credentials
      default: 'authors-secret-api'

  tasks:
    - name: info
      taskRef:
        kind: Task
        name: status
      resources:       
        inputs:
          - name: source
            resource: {{ .Values.application.name }}-git
      params:
      - name: ref
        value: $(params.ref)
      - name: repourl
        value: $(params.repourl)
      - name: repofullname
        value: $(params.repofullname)
      - name: revision
        value: $(params.revision)
      - name: author
        value: $(params.author)
      - name: message
        value: $(params.message)

    - name: prepare
      taskRef:
        name: prepare
      runAfter:
        - info
      params:
        - name: ref
          value: $(tasks.info.results.ref)
        - name: repourl
          value: $(params.repourl)
        - name: repofullname
          value: $(params.repofullname)
        - name: revision
          value: $(tasks.info.results.revision)
        - name: revision-type
          value: $(tasks.info.results.revision-type)
        - name: revision-name
          value: $(tasks.info.results.revision-name)
      resources:       
        inputs:
          - name: source
            resource: {{ .Values.application.name }}-git

    - name: helm
      taskRef:
        name: helm
      runAfter:
        - info
      params:
        - name: ref
          value: $(tasks.info.results.ref)
        - name: repourl
          value: $(params.repourl)
        - name: repofullname
          value: $(params.repofullname)
        - name: revision
          value: $(tasks.info.results.revision)
        - name: revision-type
          value: $(tasks.info.results.revision-type)
        - name: revision-name
          value: $(tasks.info.results.revision-name)
      resources:       
        inputs:
          - name: source
            resource: {{ .Values.application.name }}-git

    - name: standards
      taskRef:
        name: standards
      runAfter:
        - info
      params:
        - name: ref
          value: $(tasks.info.results.ref)
        - name: repourl
          value: $(params.repourl)
        - name: repofullname
          value: $(params.repofullname)
        - name: revision
          value: $(tasks.info.results.revision)
        - name: revision-type
          value: $(tasks.info.results.revision-type)
        - name: revision-name
          value: $(tasks.info.results.revision-name)
      resources:       
        inputs:
          - name: source
            resource: {{ .Values.application.name }}-git

    - name: docs
      taskRef:
        name: docs
      runAfter:
        - info
      params:
        - name: ref
          value: $(tasks.info.results.ref)
        - name: repourl
          value: $(params.repourl)
        - name: repofullname
          value: $(params.repofullname)
        - name: revision
          value: $(tasks.info.results.revision)
        - name: revision-type
          value: $(tasks.info.results.revision-type)
        - name: revision-name
          value: $(tasks.info.results.revision-name)
        - name: author
          value: $(tasks.info.results.author)
      resources:       
        inputs:
          - name: source
            resource: {{ .Values.application.name }}-git
        outputs:
          - name: image
            resource: {{ .Values.application.name }}-development
          - name: docs
            resource: {{ .Values.application.name }}-documentation

    - name: build
      taskRef:
        name: build
      runAfter:
        - info
      params:
        - name: ref
          value: $(tasks.info.results.ref)
        - name: repourl
          value: $(params.repourl)
        - name: repofullname
          value: $(params.repofullname)
        - name: revision
          value: $(tasks.info.results.revision)
        - name: revision-type
          value: $(tasks.info.results.revision-type)
        - name: revision-name
          value: $(tasks.info.results.revision-name)
        - name: author
          value: $(tasks.info.results.author)
      resources:       
        inputs:
          - name: source
            resource: {{ .Values.application.name }}-git
        outputs:
          - name: image
            resource: {{ .Values.application.name }}-development

    - name: deploy
      taskRef:
        name: deploy
      runAfter:
        - prepare
        - helm
        - standards
        - docs
        - build
      params:
        - name: cluster
          value: $(tasks.info.results.cluster)
        - name: ref
          value: $(tasks.info.results.ref)
        - name: revision
          value: $(tasks.info.results.revision)
        - name: revision-short
          value: $(tasks.info.results.revision-short)
        - name: revision-type
          value: $(tasks.info.results.revision-type)
        - name: revision-name
          value: $(tasks.info.results.revision-name)
        - name: author
          value: $(tasks.info.results.author)
        - name: AUTHORS_API_KEY
          value: "$(params.AUTHORS_API_KEY)"
      resources:
        inputs:
          - name: image
            resource: {{ .Values.application.name }}-development

    - name: test-stress
      taskRef:
        name: test-performance
      runAfter:
        - deploy
      params:
      - name: ref
        value: $(params.ref)
      - name: repourl
        value: $(params.repourl)
      - name: repofullname
        value: $(params.repofullname)
      - name: revision
        value: $(params.revision)
      - name: revision-type
        value: $(tasks.info.results.revision-type)
      - name: revision-name
        value: $(tasks.info.results.revision-name)

    - name: test-e2e
      taskRef:
        name: test-integration
      runAfter:
        - deploy
      params:
      - name: ref
        value: $(params.ref)
      - name: repourl
        value: $(params.repourl)
      - name: repofullname
        value: $(params.repofullname)
      - name: revision
        value: $(params.revision)
      - name: revision-type
        value: $(tasks.info.results.revision-type)
      - name: revision-name
        value: $(tasks.info.results.revision-name)
      resources:
        inputs:
          - name: source
            resource: {{ .Values.application.name }}-git

    # todo: upgrade based on semantic versioning principles
    # only minor supported and patch
    # develop       : deploys to dev development environment with commit hash tagged
    # feature/test  : does not deploy to development environment
    # release/1.0.0 : rolls out slowly to canary/production
    # hotfix/1.0.1  : imediately deployment to canary/production
    # patch/1.0.2   : imediately deployment to canary/production (can be a patch to a small subset of pods only)
    # pr/1          : build, test and report back to pr

    - name: promote
      conditions:
        - conditionRef: is-allowed-production
          params:
            - name: revision-type
              value: $(tasks.info.results.revision-type)
      taskRef:
        name: promote
      runAfter:
        - test-e2e
        - test-stress
      params:
      - name: cluster
        value: $(tasks.info.results.cluster)
      - name: repofullname
        value: $(params.repofullname)
      - name: ref
        value: $(tasks.info.results.ref)
      - name: revision
        value: $(tasks.info.results.revision)
      - name: revision-short
        value: $(tasks.info.results.revision-short)
      - name: revision-type
        value: $(tasks.info.results.revision-type)
      - name: revision-name
        value: $(tasks.info.results.revision-name)
      - name: author
        value: $(params.author)
      - name: email
        value: $(params.email)
      - name: AUTHORS_API_KEY
        value: $(params.AUTHORS_API_KEY)
      resources:
        inputs:
          - name: source
            resource: {{ .Values.application.name }}-git
          - name: image
            resource: {{ .Values.application.name }}-development
        outputs:
          - name: image
            resource: {{ .Values.application.name }}-production

    - name: release
      taskRef:
        kind: Task
        name: tag
      runAfter:
        - promote
      params:
      - name: author
        value: $(params.author)
      - name: email
        value: $(params.email)
      - name: revision-type
        value: $(tasks.info.results.revision-type)
      - name: revision-name
        value: $(tasks.info.results.revision-name)
      resources:
        inputs:
          - name: source
            resource: {{ .Values.application.name }}-git