apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: {{ .Values.application.name }}
  namespace: {{ .Values.application.environments.cicd }}
  labels:
    app: {{ .Values.application.name }}
spec:
  workspaces:
    - name: {{ .Values.application.name }}-source
      description: The git repo will be cloned onto the volume backing this workspace
    - name: {{ .Values.application.name }}-shared
      description: shared folder
  resources:
    - name: {{ .Values.application.name }}-git
      type: git
    - name: {{ .Values.application.name }}-development
      type: image
    - name: {{ .Values.application.name }}-production
      type: image
    - name: {{ .Values.application.name }}-documentation
      type: image
  params:
    - name: ref
      description: Ref of the application
    - name: revision
      description: git unique head commit id
    - name: repourl
      description: repository full name
    - name: repofullname
      description: repository full name
    - name: author
      description: commit author username
    - name: email
      description: commit author email
    - name: message
      description: commit message

  tasks:

    - name: git
      taskRef:
        name: git-clone
      workspaces:
      - name: output
        workspace: {{ .Values.application.name }}-source
      params:
      - name: verbose
        value: "false"
      - name: url
        value: $(params.repourl)
      - name: revision
        value: $(params.revision)
      - name: ref
        value: $(params.ref)
      - name: repourl
        value: $(params.repourl)
      - name: repofullname
        value: $(params.repofullname)
      - name: author
        value: $(params.author)
      - name: message
        value: $(params.message)

    - name: standards
      taskRef:
        name: standards
      runAfter:
        - git
      workspaces:
      - name: source
        workspace: {{ .Values.application.name }}-source
      params:
        - name: ref
          value: $(tasks.git.results.ref)
        - name: repourl
          value: $(params.repourl)
        - name: repofullname
          value: $(params.repofullname)
        - name: revision
          value: $(tasks.git.results.revision)
        - name: revision-type
          value: $(tasks.git.results.revision-type)
        - name: revision-name
          value: $(tasks.git.results.revision-name)

    - name: docs
      taskRef:
        name: docs
      runAfter:
        - standards
      params:
        - name: ref
          value: $(tasks.git.results.ref)
        - name: repourl
          value: $(params.repourl)
        - name: repofullname
          value: $(params.repofullname)
        - name: revision
          value: $(tasks.git.results.revision)
        - name: revision-type
          value: $(tasks.git.results.revision-type)
        - name: revision-name
          value: $(tasks.git.results.revision-name)
        - name: author
          value: $(tasks.git.results.author)

    - name: build
      taskRef:
        name: build
      runAfter:
        - standards
      workspaces:
      - name: source
        workspace: {{ .Values.application.name }}-source
      params:
        - name: ref
          value: $(tasks.git.results.ref)
        - name: repourl
          value: $(params.repourl)
        - name: repofullname
          value: $(params.repofullname)
        - name: revision
          value: $(tasks.git.results.revision)
        - name: revision-type
          value: $(tasks.git.results.revision-type)
        - name: revision-name
          value: $(tasks.git.results.revision-name)

    - name: deploy
      taskRef:
        name: deploy
      runAfter:
        - docs
        - build
      workspaces:
      - name: source
        workspace: {{ .Values.application.name }}-source
      params:
        - name: cluster
          value: {{ .Values.cluster }}
        - name: ref
          value: $(tasks.git.results.ref)
        - name: revision
          value: $(tasks.git.results.revision)
        - name: revision-short
          value: $(tasks.git.results.revision-short)
        - name: revision-type
          value: $(tasks.git.results.revision-type)
        - name: revision-name
          value: $(tasks.git.results.revision-name)
        # - name: image
        #   value: $(tasks.build.results.image)
        # - name: documentation
        #   value: $(tasks.docs.results.image)
          
    - name: test-stress
      taskRef:
        name: test-performance
      runAfter:
        - deploy
      params:
      - name: ref
        value: $(params.ref)
      - name: repourl
        value: $(params.repourl)
      - name: repofullname
        value: $(params.repofullname)
      - name: revision
        value: $(params.revision)
      - name: revision-type
        value: $(tasks.git.results.revision-type)
      - name: revision-name
        value: $(tasks.git.results.revision-name)

    - name: test-e2e
      taskRef:
        name: test-integration
      runAfter:
        - deploy
      workspaces:
      - name: source
        workspace: {{ .Values.application.name }}-source
      params:
      - name: ref
        value: $(params.ref)
      - name: repourl
        value: $(params.repourl)
      - name: repofullname
        value: $(params.repofullname)
      - name: revision
        value: $(params.revision)
      - name: revision-type
        value: $(tasks.git.results.revision-type)
      - name: revision-name
        value: $(tasks.git.results.revision-name)

    - name: apply
      # conditions:
      #   - conditionRef: is-allowed-production
      #     params:
      #       - name: revision-type
      #         value: $(tasks.git.results.revision-type)
      taskRef:
        name: apply
      runAfter:
        - test-e2e
        - test-stress
      workspaces:
      - name: source
        workspace: {{ .Values.application.name }}-source
      params:
      - name: repofullname
        value: $(params.repofullname)
      - name: ref
        value: $(tasks.git.results.ref)
      - name: revision
        value: $(tasks.git.results.revision)
      - name: revision-short
        value: $(tasks.git.results.revision-short)
      - name: revision-type
        value: $(tasks.git.results.revision-type)
      - name: revision-name
        value: $(tasks.git.results.revision-name)

    - name: promote
      # conditions:
      #   - conditionRef: is-allowed-production
      #     params:
      #       - name: revision-type
      #         value: $(tasks.git.results.revision-type)
      taskRef:
        name: promote
      runAfter:
        - apply
      workspaces:
      - name: source
        workspace: {{ .Values.application.name }}-source
      params:
      - name: cluster
        value: $(tasks.git.results.cluster)
      - name: repofullname
        value: $(params.repofullname)
      - name: ref
        value: $(tasks.git.results.ref)
      - name: revision
        value: $(tasks.git.results.revision)
      - name: revision-short
        value: $(tasks.git.results.revision-short)
      - name: revision-type
        value: $(tasks.git.results.revision-type)
      - name: revision-name
        value: $(tasks.git.results.revision-name)
      - name: author
        value: $(params.author)
      - name: email
        value: $(params.email)
      - name: image
        value: $(tasks.build.results.image)

    - name: release
      taskRef:
        name: tag
      runAfter:
        - promote
      workspaces:
      - name: source
        workspace: {{ .Values.application.name }}-source
      params:
      - name: author
        value: $(params.author)
      - name: email
        value: $(params.email)
      - name: revision-type
        value: $(tasks.git.results.revision-type)
      - name: revision-name
        value: $(tasks.git.results.revision-name)