apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    description: Gitea's HTTP route
  labels:
    app: {{ .Values.name | default 'gitea' | quote }}
  name: {{ .Values.name | default 'gitea' | quote }}
spec:
  host: {{ required "You MUST specify the external hostname to be used for the public-facing web page" .Values.hostname }}
  to:
    kind: Service
    name: {{ .Values.name | default 'gitea' | quote }}
    weight: 100
  wildcardPolicy: None
status: {}