{{- if .Values.buildconfigs }}
{{- range $key := .Values.buildconfigs }}
---
kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: {{ .name }}
  labels:
    build: {{ .name }}
    type: image
spec:
  triggers:
  - type: "ConfigChange"
{{- if .build_trigger_secret }}
  - type: GitHub
    github:
      secret: {{ .build_trigger_secret | quote }}
  - type: GitLab
    gitlab:
      secret: {{ .build_trigger_secret | quote }}
  - type: BitBucket
    bitbucket:
      secret: {{ .build_trigger_secret | quote }}
  - type: Generic
    generic:
      secret: {{ .build_trigger_secret | quote }}
      allowEnv: true
  {{- end}}
  runPolicy: Serial
  source:
    type: Git
    {{- if .source_secret }}
    sourceSecret:
      name: {{ .source_secret }}
    {{- end }}
    git:
      uri: {{ .source_repo  | default "https://github.com/redhat-cop/containers-quickstarts"  | quote }}
      ref: {{ .source_repo_ref | default "main" | quote }}
    {{- if .source_context_dir }}
    contextDir: {{ .source_context_dir | quote }}
    {{- else }}
    contextDir: "jenkins-agents/{{ .name }}"
    {{- end }}
  strategy:
{{- if .strategy_type }}
    type: {{ .strategy_type }}
    sourceStrategy:
      from:
        kind: {{ .builder_image_kind | default "ImageStreamTag" }}
        name:  "{{ .builder_image_name }}:{{ .builder_image_tag }}"
{{- else }}
    type: Docker
    dockerStrategy:
      dockerfilePath: {{ .dockerfilePath | default "Dockerfile" | quote }}
      {{- if .builder_image_name }}
      from:
        kind: DockerImage
        name: "{{ .builder_image_name }}:{{ .builder_image_tag }}"
      {{- end }}
{{- end }}
    {{- if .pull_secret }}
      pullSecret:
        name: {{ .pull_secret | quote}}
    {{- end }}
  output:
    to:
      kind: ImageStreamTag
      name: "{{ .name }}:latest"
{{- end}}
{{- end}}
